# JSON Schema <http://json-schema.org/>
#
# Describes messages received from Telescreen.
#
---
oneOf:
  # status
  - type: object
    additionalProperties: false
    required: [id, type]
    properties:
      id: &UUID
        type: string
        pattern: '^[0-9a-f]{32}$'
      type: {enum: [status]}
      status:
        type: object
        additionalProperties: false
        required: [session, power, type]
        properties:
          session: *UUID
          power: {type: boolean}
          type: {enum: [full, right, both]}
          urlRight: {type: string, pattern: '://'}
          urlBottom: {type: string, pattern: '://'}

# EOF
