# JSON Schema <http://json-schema.org/>
#
# Describes messages received from Telescreen.
#
---
type: object
additionalProperties: false
required: [id, type, status]
properties:
  id: {$ref: '#/definitions/uuid'}
  type: {enum: [status]}
  status: {$ref: '#/definitions/status'}

definitions:
  uuid:
    type: string
    pattern: '^[0-9a-f]{32}$'

  url:
    type: string
    pattern: '://'

  power:
    enum: ['on', 'standby', 'to-on', 'to-standby', 'unknown']

  status:
    type: object
    additionalProperties: false
    required: [plan, power, layout]
    properties:
      plan: {$ref: '#/definitions/uuid'}
      power: {$ref: '#/definitions/power'}
      layout: {$ref: '#/definitions/layout'}

  layout:
    type: object
    additionalProperties: false
    required: [mode]
    properties:
      mode: {enum: [full, sidebar, panel]}

      sidebar:
        oneOf:
          - enum: [null]
          - {$ref: '#/definitions/url'}

      panel:
        oneOf:
          - enum: [null]
          - {$ref: '#/definitions/url'}

# EOF
